keypang/SWE-YutGame

- SWE-YUT/.gitignore
- SWE-YUT/.idea/.gitignore
- SWE-YUT/.idea/misc.xml
- SWE-YUT/.idea/modules.xml
- SWE-YUT/.idea/vcs.xml
- SWE-YUT/SWE-YUT.iml
- SWE-YUT/src/Main.java
- SWE-YUT/src/controller/StartScreenController.java
- SWE-YUT/src/model/BoardType.java
- SWE-YUT/src/model/Model.java
- SWE-YUT/src/model/StartInfo.java
- SWE-YUT/src/view/GameView.java
- SWE-YUT/src/view/SwingView.java
SWING 으로 윷놀이 게임 설정화면을 제작하고,
컨트롤러가 모델과 뷰 사이의 데이터 전달 또한 정상적으로 수행하고 있는 것도 확인하였습니다.
테스트 코드이니 앞으로 수정이 더 필요합니다.
> [#1]Feat:게임 설정 컨트롤러 및 게임 설정 화면(SWING) 기본 설계

- src/controller/GameScreenController.java
- src/model/GameManager.java
- src/model/StartInfo.java
- src/model/Yut.java
- src/model/YutResult.java
- test/controller/YutThrowTest.java
- test/model/YutThrowTest1.java
**<코드 수정 사항>**
- 윷 로직 한글로 변경함에 따라 VIEW-CONTROLLER-MODEL간 한글로 주고 받으면 됨.
ㄴ 도, 개, 걸, 윷, 모 이런 식으로
- GAMEMANAGER 필요한 코드 수정
> [REFECTOR] 윷 로직 수정 및 GAMEMANAGER 코드 수정 #11

- src/controller/GameScreenController.java
- src/model/GameManager.java
<기능 구현>
- 윷 로직 최종 수정 및 윷 던지고 나서 상태 보드판에 연결
- 추가 적으로 수정해야 할 사항들 주석 처리 해놓았음.
일단 일차적인 구현은 끝났고 MODEL쪽 추가 함수 기능 구현 이후 CONTROLLER 연결 진행
> [REFECTOR] 2th GAMEMANAGER 코드 수정

- .idea/misc.xml
- src/Main.java
- src/controller/GameScreenController.java
- src/controller/StartScreenController.java
- src/model/YutResult.java
- src/view/GameConfigView.java
- src/view/GamePlayView.java
- src/view/SwingConfigScreen.java
- src/view/SwingPlayScreen.java
- test/controller/YutThrowTest.java
메인 게임화면 윷 던지기 버튼 기능을 추가했습니다.
뷰 관련 클래스 이름을 일부 변경했습니다.
뷰 테스트를 위해 컨트롤러에 코드를 추가하여 테스트 진행하였습니다.
검토해보시고, 문제점이 있거나 추가해야할 사항이 있다면 알려주세요.
추가적으로, 윷 결과에 따른 이미지 출력 기능을 추후 추가할 예정입니다.
> [FEAT][REFACTOR] 메인 게임화면 윷 던지기 버튼 기능 추가 및 뷰 관련 클래스 이름 변경 / 뷰-컨트롤러 연동 테스트

- src/Main.java
- src/model/Board.java
- src/model/Cell.java
- src/model/Piece.java
동일 플레이어 말 업기
타 플레이어 말 잡기
완주
이동 가능한 Id 값 반환
> [#26] FEAT: 말 충돌 구현 및 완주 구현

- src/Main.java
- src/model/Board.java
- src/model/Piece.java
> [FEAT] 말 동시 이동 구현

- src/model/Board.java
- test/model/BoardTest.java
> [TEST] Model JUnit 테스트

- src/controller/GameScreenController.java
- src/model/GameManager.java
- src/view/SwingPlayScreen.java
Relates to https://github.com/keypang/SWE-YutGame/issues/31
컨트롤러 모델 연결 후 쌍방향 오류 체크를 위한 pr
> [Feat] controller를 model과 최초 연결

- SWE-YutGame.iml
- src/view/SwingPlayScreen.java
- 말 꺼내기 버튼을 삭제하였습니다.
- 전체 갱신 메서드를 생성하여 말을repaint하는 메서드를 추가했습니다.
> [#47] 전체 말 갱신 메서드 구현 및 UI 개선

- SWE-YutGame.iml
- src/controller/GameScreenController.java
- src/model/Board.java
- src/model/GameManager.java
- src/view/GamePlayView.java
- src/view/SwingPlayScreen.java
- test/controller/YutThrowTest.java
Relates to #31 
턴 관련 오류 수정 및
기타 메서드 수정
> [Refector] controller를 model과 view연결 하는 과정에서의 오류 수정

- src/model/Board.java
- test/model/BoardTest.java
> FIX: 완주 처리 오류 수정

- src/model/Board.java
> FIX: 미출발 Piece 백도 오류 수정

- src/view/SwingPlayScreen.java
오각형 윷판에 대한 좌표 매핑을 추가하였습니다.
로직상 영향 주는 코드가 아니므로, 누구나 병합해도 됩니다.
> [#62][UI] 오각형 윷판에 대한 좌표 매핑 추가

- src/model/Board.java
- src/model/Cell.java
- src/model/Piece.java
- test/model/BoardTest.java
> Feat: 규칙에 맞는 지름길 로직

- src/controller/GameScreenController.java
RELATES TO #31 
윷 리스트가 말을 선택한 후 바로바로 업데이트가 안되어서 이를 수정하였음
> [REFECTOR] #31 윷 리스트 바로바로 업데이트 안되는 거 수정

- src/model/Board.java
- test/model/BoardTest.java
> FIX: 실제 이동 오류 수정

- src/model/GameManager.java
Reverts keypang/SWE-YutGame#76
> Revert "[FEAT] 완주 셀로 이동 가능한 윷 리스트 반환 구현"

- src/controller/GameScreenController.java
- src/controller/StartScreenController.java
- src/model/Board.java
- src/model/BoardType.java
- src/model/Cell.java
- src/model/GameManager.java
- src/model/Piece.java
- src/model/Player.java
- src/model/PositionDTO.java
- src/model/StartInfo.java
- src/model/Yut.java
- src/model/YutResult.java
- src/view/GameConfigView.java
- src/view/GamePlayView.java
- src/view/SelectYutResultScreen.java
- src/view/SwingConfigScreen.java
- src/view/SwingPlayScreen.java
- test/model/GameManagerTest.java
통일되어 있지 않던 변수명 명명법을 camel 표기법으로 변경하였습니다.
코드 컨벤션을 일괄적으로 통일시켰습니다.
뷰 코드에서 사용이 되지 않는 메소드를 삭제하고, 주석된 부분을 일부 삭제하였습니다.
> [#87][REFACOTR] 코드 컨벤션 적용 

- src/model/Yut.java
- src/view/GamePlayView.java
- src/view/SelectYutResultScreen.java
- src/view/SwingPlayScreen.java
> [REFACTOR] 불필요한 IMPORT 삭제

- src/view/SelectYutResultScreen.java
- src/view/SwingPlayScreen.java
- 지정 윷, 윷 선택 시 X버튼 안 눌리게 수정 (X버튼 비활성화)
- 지정 윷 선택하면 깜빡거리는 현상 수정 (JFrame에서 JDialog로 교체하여 해결)
- 턴 넘어갈 시 턴 시작 메세지 노출되는 효과 추가
> [FEAT] [UI] 새 Dialog 메세지 추가 및 기존 오류 수정

- META-INF/MANIFEST.MF
- src/model/GameManager.java
#95 
Java Docs를 사용해 구현했던 메소드들에 대한 간략한 설명을 작성하였습니다.
프로젝트 보고서 작성을 위해 이해를 돕기 위한 목적으로 작성하였습니다.
| 클래스 | 메소드 |
|--|--|
|![image](https://github.com/user-attachments/assets/071b3af2-6b51-41ee-aeb5-c37ed197f090)|![image](https://github.com/user-attachments/assets/c3129643-44d8-4d00-8a72-5ff4d285a290)|
> [DOCS] 구현 메소드에 대한 설명 작성

- pom.xml
- src/main/java/JavaFxMain.java
pom.xml 에 javafx 관련 의존성을 추가하고, 실행까지 완료하였습니다. 
------
JavaFxMain 실행법 
1. 위 사진의 1번 -> 2번 순서대로 클릭
2. mvn clean javafx:run 입력
> [BUILD] pom.xml 에 javafx 관련 의존성 추가

- src/JavaFxMain.java
- src/controller/StartScreenController.java
- src/view/JavaFxConfigScreen.java
관련이슈 : #104 
기존에 제작된 화면은 UI 구현만 되어있는 상태였습니다.
컨트롤러와의 연결을 완료하였습니다.
또한, 설정화면은 GameConfigView 인터페이스를 구현하도록 수정했습니다.
close : #104
> [#104][FEAT] javafx UI 와 컨트롤러 연결 

- src/view/JavaFxPlayScreen.java
관련 이슈 : #106 
현재, javaFx 버전 게임플레이 화면이 구현 완료되었습니다.
단, 사각형 판에서만 정상적으로 플레이 가능합니다.
오각형, 육각형 판에서도 로직은 적용되나 말 판의 위치 등 UI 에서 수정이 필요합니다.
close : #106
> [#106][FEAT][UI] javaFx 버전 게임플레이 화면 구현 완료(사각형)

- src/view/JavaFxPlayScreen.java
- src/view/JavaFxSelectYutResultScreen.java
- 오각형, 육각형 맵에서도 정상적인 플레이가 가능하도록 코드를 추가하였습니다.
- 윷 결과 이미지를 로드하는데, 로딩 시간에 관한 오류가 있어 이를 해결하는 코드를 추가했습니다.
> [FEAT] [UI] 오각형, 육각형 좌표 구현 및 이미지 로드 코드 추가

- src/model/GameManager.java
- src/view/javafx/JavaFxPlayScreen.java
- 재시작 시 말이 안 움직이는 버그와 윷 결과 이미지가 로드되지 않는 버그를 해결하였습니다.
> [FIX] 재시작 및 이미지 로드 버그 해결

- test/controller/YutThrowTest.java
- test/model/BoardTest.java
- test/model/GameManagerTest.java
컨트롤러 테스트 코드 리펙토링
SETUP 함수와 테스트 함수로 나누고 내용 추가 하였음.
> [REFACTOR] 컨트롤러 테스트 코드 리펙토링
